edition = "2021"
version = "Two"
unstable_features = true

max_width = 160
hard_tabs = true
tab_spaces = 4
newline_style = "Unix"

wrap_comments = true
format_code_in_doc_comments = true
comment_width = 120
doc_comment_code_block_width = 120
normalize_comments = true

use_small_heuristics = "Off"
fn_call_width = 140
attr_fn_like_width = 112
struct_lit_width = 36
struct_variant_width = 60
array_width = 120
chain_width = 90
single_line_if_else_max_width = 96

reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
trailing_comma = "Never"
match_block_trailing_comma = false
format_macro_bodies = true
use_try_shorthand = true
use_field_init_shorthand = true
merge_derives = true
force_explicit_abi = true
